[0m09:41:03.581348 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022DED5C8290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022DED5C8110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022DED5C80B0>]}


============================== 09:41:03.587637 | 6a825372-c79c-4393-b665-d8ed1d3165c6 ==============================
[0m09:41:03.587637 [info ] [MainThread]: Running with dbt=1.7.9
[0m09:41:03.591293 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\flore\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt init', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m09:41:22.557479 [debug] [MainThread]: Starter project path: C:\Users\flore\Documents\DBT_WILD\DBT-PROJECT\my-dbt-env\Lib\site-packages\dbt\include\starter_project
[0m09:41:22.585264 [info ] [MainThread]: 
Your new dbt project "dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m09:41:22.622686 [info ] [MainThread]: Setting up your profile.
[0m09:41:25.957206 [debug] [MainThread]: Command `dbt init` succeeded at 09:41:25.957206 after 22.59 seconds
[0m09:41:25.957206 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022DED442540>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022DED419EE0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000022DED6248C0>]}
[0m09:41:25.961520 [debug] [MainThread]: Flushing usage events
[0m10:33:36.161849 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021343EC97F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021343ECAC30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021343EC94C0>]}


============================== 10:33:36.171892 | b1e145a0-f971-4cef-a54a-c7c1d53bdb85 ==============================
[0m10:33:36.171892 [info ] [MainThread]: Running with dbt=1.7.9
[0m10:33:36.171892 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\flore\\.dbt', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m10:33:36.179657 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\flore\Documents\DBT_WILD\DBT-PROJECT\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m10:33:36.181690 [debug] [MainThread]: Command `dbt run` failed at 10:33:36.181690 after 1.14 seconds
[0m10:33:36.183824 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021343CDB230>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021343EC8F80>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021343EC9F40>]}
[0m10:33:36.185429 [debug] [MainThread]: Flushing usage events
